#!/bin/sh

[ -f /var/run/fw4.state ] || exit 0
[ "$ACTION" = add ] || exit 0
OFFLOAD=$(uci -q get firewall.@defaults[0].flow_offloading_hw || exit 0)
[ $OFFLOAD -ne 0 ] || exit 0
nft add flowtable inet fw4 ft { hook ingress priority 0 \; devices = { "$DEVICENAME" } \; flags offload \; } && logger -t firewall "Added $DEVICENAME to flowtable due to reload"
