#!/bin/sh

UCI=$(which uci)
UCIG="$UCI -q get"
UCIS="$UCI set"
LAN="network.lan"
GUEST="network.guest"

wan_ip=$1
wan_mask=$2

netclash=$($UCIG $LAN.netclash 2>/dev/null)
[ "x$netclash" = "x1" ] && exit
lan_ip=$($UCIG $LAN.ipaddr)
lan_mask=$($UCIG $LAN.netmask)
guest=$($UCIG $GUEST.ifname 2>/dev/null)

[ "$wan_mask" \> "$lan_mask" ] && mask=$lan_mask || mask=$wan_mask
eval $(echo $mask | awk -F '.' '{print "mask1=" $1 ";mask2=" $2 ";mask3=" $3 ";mask4=" $4}')
eval $(echo $lan_ip | awk -F '.' '{print "lan_ip1=" $1 ";lan_ip2=" $2 ";lan_ip3=" $3 ";lan_ip4=" $4}')
eval $(echo $wan_ip | awk -F '.' '{print "wan_ip1=" $1 ";wan_ip2=" $2 ";wan_ip3=" $3 ";wan_ip4=" $4}')

get_sub(){
	for i in 1 2 3 4
	do
		eval "sub$1$i=\$((\$${1}_ip$i & \$mask$i))"
	done
}

get_sub lan
get_sub wan

# when LAN and WAN are in the same network segment, the LAN network segment will +1.
# if LAN and WAN are in different net segment, the LAN network segment will remain unchanged.
if [ "$sublan1$sublan2$sublan3$sublan4" = "$subwan1$subwan2$subwan3$subwan4" ];then
	if [ "x$sublan1" = "x192" ]; then
		[ "x$wan_mask" != "x255.255.255.0" ] && exit 0
		if [ "x$sublan3" = "x254" ];then
			new_lan="$sublan1.$sublan2.1.1"
		else
			new_lan="$sublan1.$sublan2.$(($sublan3+1)).1"
		fi
		new_mask=255.255.255.0
	else
		new_lan=192.168.1.1
		new_mask=255.255.255.0
	fi

	$UCIS $LAN.ipaddr=$new_lan
	$UCIS $LAN.netmask=$new_mask
	$UCI commit

	sleep 1
	/etc/init.d/network restart >/dev/null 2>&1
	exit 0
fi
