#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz && sync

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done

	# auto load EasyMesh if enable
	if [ "$(uci -q get easymesh.status.enable)" == "1" ]; then
		echo "========Auto Load Easymesh===="
		sf_easymesh load auto_load &
	fi
}
