#ifndef _PCIE_TOP_REG_H_
#define _PCIE_TOP_REG_H_

#define CO_BIT(pos) (1U << (pos))

#define TOP_BROM_RESET_E902_SYSM_RESET_N         (CO_BIT(0))
#define TOP_BROM_RESET_C906_24G_SYSM_RESET_N     (CO_BIT(1))
#define TOP_BROM_RESET_C906_5G_SYSM_RESET_N      (CO_BIT(3))
#define TOP_BROM_RESET_CRM_SYSM_RESET_N          (CO_BIT(4))
#define TOP_BROM_RESET_DFE_SYSM_RESET_N          (CO_BIT(5))
#define TOP_BROM_RESET_PCIE_SYSM_RESET_N         (CO_BIT(6))
#define TOP_BROM_RESET_PIF_SYSM_RESET_N          (CO_BIT(7))
#define TOP_BROM_RESET_PIN_SYSM_RESET_N          (CO_BIT(8))
#define TOP_BROM_RESET_WLAN_24G_SYSM_RESET_N     (CO_BIT(9))
#define TOP_BROM_RESET_WLAN_5G_SYSM_RESET_N      (CO_BIT(10))
#define TOP_BROM_RESET_EFUSE_SYSM_RESET_N        (CO_BIT(11))
#define TOP_BROM_RESET_AMU_SYSM_RESET_N          (CO_BIT(12))

#define TOP_CRM_RSTN_IROM_SW_RST_N               (CO_BIT(14))
#define TOP_CRM_RSTN_UART_REF_SW_RST_N           (CO_BIT(10))
#define TOP_CRM_RSTN_AXI_MCU_SW_RST_N            (CO_BIT(9))
#define TOP_CRM_RSTN_AXI_MAC_SW_RST_N            (CO_BIT(8))
#define TOP_CRM_RSTN_APB_SW_RST_N                (CO_BIT(7))
#define TOP_CRM_RSTN_IRAM_SW_RST_N               (CO_BIT(6))
#define TOP_CRM_RSTN_WLAN_LB_PLF_SW_RST_N        (CO_BIT(3))
#define TOP_CRM_RSTN_SPL_MASTER_SW_RST_N         (CO_BIT(2))
#define TOP_CRM_RSTN_CMN_BUS_SW_RST_N            (CO_BIT(1))
#define TOP_CRM_RSTN_FAST_ITF_SW_RST_N           (CO_BIT(0))

#define TOP_CRM_HB_RSTN_WLAN_HB_PLF_SW_RST_N     (CO_BIT(0))

#define TOP_CRM_CLKEN_UART_REF_CLK_EN            (CO_BIT(18))
#define TOP_CRM_CLKEN_C906_5G_CLK_EN             (CO_BIT(16))
#define TOP_CRM_CLKEN_C906_24G_CLK_EN            (CO_BIT(15))
#define TOP_CRM_CLKEN_E902_CLK_EN                (CO_BIT(14))
#define TOP_CRM_CLKEN_AXI_MCU_CLK_EN             (CO_BIT(13))
#define TOP_CRM_CLKEN_AXI_MAC_CLK_EN             (CO_BIT(12))
#define TOP_CRM_CLKEN_APB_CLK_EN                 (CO_BIT(11))
#define TOP_CRM_CLKEN_IRAM_CLKEN                 (CO_BIT(10))
#define TOP_CRM_CLKEN_WLAN_LB_PLF_CLK_EN         (CO_BIT(7))
#define TOP_CRM_CLKEN_WLAN_24G_LP_ROOT_CLK_EN    (CO_BIT(5))
#define TOP_CRM_CLKEN_WLAN_LB_REF_CLK_EN         (CO_BIT(3))
#define TOP_CRM_CLKEN_SPI_MASTER_CLK_EN          (CO_BIT(2))
#define TOP_CRM_CLKEN_CMN_BUS_CLK_EN             (CO_BIT(1))
#define TOP_CRM_CLKEN_FAST_ITF_CLK_EN            (CO_BIT(0))

#define TOP_CRM_HB_CLKEN_WLAN_HB_PLF_CLK_EN      (CO_BIT(8))
#define TOP_CRM_HB_CLKEN_WLAN_5G_LP_ROOT_CLK_EN  (CO_BIT(4))
#define TOP_CRM_HB_CLKEN_WLAN_HB_REF_CLK_EN      (CO_BIT(0))

#define TOP_BROM_RESET_WIFI_C906_5G                                                  \
    (TOP_BROM_RESET_C906_5G_SYSM_RESET_N  | TOP_BROM_RESET_PCIE_SYSM_RESET_N      |  \
     TOP_BROM_RESET_CRM_SYSM_RESET_N      | TOP_BROM_RESET_C906_5G_SYSM_RESET_N   |  \
     TOP_BROM_RESET_E902_SYSM_RESET_N     | TOP_BROM_RESET_WLAN_5G_SYSM_RESET_N)

#define TOP_BROM_RESET_WIFI_C906_24G                                                 \
    (TOP_BROM_RESET_WLAN_24G_SYSM_RESET_N | TOP_BROM_RESET_PCIE_SYSM_RESET_N      |  \
     TOP_BROM_RESET_CRM_SYSM_RESET_N      | TOP_BROM_RESET_C906_24G_SYSM_RESET_N  |  \
     TOP_BROM_RESET_E902_SYSM_RESET_N)

#define TOP_CRM_HB_CLKEN_WIFI_C906_5G                                                \
    (TOP_CRM_HB_CLKEN_WLAN_HB_PLF_CLK_EN  | TOP_CRM_HB_CLKEN_WLAN_HB_REF_CLK_EN   |  \
     TOP_CRM_HB_CLKEN_WLAN_5G_LP_ROOT_CLK_EN)

#define TOP_CRM_CLKEN_WIFI_C906_5G                                                   \
    (TOP_CRM_CLKEN_C906_5G_CLK_EN         | TOP_CRM_CLKEN_APB_CLK_EN              |  \
     TOP_CRM_CLKEN_IRAM_CLKEN)

#define TOP_CRM_CLKEN_WIFI_C906_24G                                                  \
    (TOP_CRM_CLKEN_C906_24G_CLK_EN        | TOP_CRM_CLKEN_WLAN_24G_LP_ROOT_CLK_EN |  \
     TOP_CRM_CLKEN_IRAM_CLKEN             | TOP_CRM_CLKEN_WLAN_LB_PLF_CLK_EN      |  \
     TOP_CRM_CLKEN_APB_CLK_EN             | TOP_CRM_CLKEN_WLAN_LB_REF_CLK_EN)

#define TOP_CRM_HB_RSTN_WIFI_C906_5G                                                 \
    (TOP_CRM_HB_RSTN_WLAN_HB_PLF_SW_RST_N)

#define TOP_CRM_RSTN_WIFI_C906_5G                                                    \
    (TOP_CRM_RSTN_IROM_SW_RST_N           | TOP_CRM_RSTN_IRAM_SW_RST_N            |  \
     TOP_CRM_HB_RSTN_WLAN_HB_PLF_SW_RST_N)

#define TOP_CRM_RSTN_WIFI_C906_24G                                                   \
    (TOP_CRM_RSTN_IROM_SW_RST_N           | TOP_CRM_RSTN_IRAM_SW_RST_N            |  \
     TOP_CRM_RSTN_WLAN_LB_PLF_SW_RST_N)

#define CPU_SYSM_BASE_ADDR                 (0x01e00000)
#define BROM_SYSM_RESET_CPU_OFFSET         (0x00000030)
#define BROM_SYSM_RESET_ADDR               (CPU_SYSM_BASE_ADDR + 0x00000030)
#define BROM_SYSM_MEM_CONTROL_ADDR         (CPU_SYSM_BASE_ADDR + 0x00000034)

#define TOP_CRM_CLKEN_CFG_OFFSET           (0x0000048c)
#define TOP_CRM_HB_CLKEN_CFG_OFFSET        (0x00000508)
#define TOP_CRM_CLKEN_CFG_ADDR             (CPU_SYSM_BASE_ADDR + 0x0000048c)
#define TOP_CRM_HB_CLKEN_CFG_ADDR          (CPU_SYSM_BASE_ADDR + 0x00000508)

#define TOP_CRM_RSTN_CFG_OFFSET            (0x000004c0)
#define TOP_CRM_HB_RSTN_CFG_OFFSET         (0x0000050c)
#define TOP_CRM_RSTN_CFG_ADDR              (CPU_SYSM_BASE_ADDR + 0x000004c0)
#define TOP_CRM_HB_RSTN_CFG_ADDR           (CPU_SYSM_BASE_ADDR + 0x0000050c)

#define CPU_C906_5G_SYSM_BASE_ADDR         (0x00001800)
#define CPU_C906_24G_SYSM_BASE_ADDR        (0x00001000)

#define CPU_C906_SYSM_CLK_DIV_OFFSET       (0x0)
#define CPU_C906_SYSM_RSTN_OFFSET          (0x4)
#define CPU_C906_SYSM_CLK_EN_OFFSET        (0x8)
#define CPU_C906_SYSM_RVBA0_OFFSET         (0xC)
#define CPU_C906_SYSM_RVBA1_OFFSET         (0x10)
#define CPU_C906_SYSM_BASE0_OFFSET         (0x14)
#define CPU_C906_SYSM_SYNC_RESET_OFFSET    (0x28)

#define CPU_C906_5G_SYSM_RST_ADDR          (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_RSTN_OFFSET)
#define CPU_C906_5G_SYSM_CLK_EN_ADDR       (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_CLK_EN_OFFSET)
#define CPU_C906_5G_SYSM_RVBA0_ADDR        (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_RVBA0_OFFSET)
#define CPU_C906_5G_SYSM_RVBA1_ADDR        (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_RVBA1_OFFSET)
#define CPU_C906_5G_SYSM_BASE0_ADDR        (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_BASE0_OFFSET)
#define CPU_C906_5G_SYSM_SYNC_RESET_ADDR   (CPU_C906_5G_SYSM_BASE_ADDR + CPU_C906_SYSM_SYNC_RESET_OFFSET)

#define CPU_C906_24G_SYSM_RST_ADDR         (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_RSTN_OFFSET)
#define CPU_C906_24G_SYSM_CLK_EN_ADDR      (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_CLK_EN_OFFSET)
#define CPU_C906_24G_SYSM_RVBA0_ADDR       (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_RVBA0_OFFSET)
#define CPU_C906_24G_SYSM_RVBA1_ADDR       (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_RVBA1_OFFSET)
#define CPU_C906_24G_SYSM_BASE0_ADDR       (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_BASE0_OFFSET)
#define CPU_C906_24G_SYSM_SYNC_RESET_ADDR  (CPU_C906_24G_SYSM_BASE_ADDR + CPU_C906_SYSM_SYNC_RESET_OFFSET)

#endif /* _PCIE_TOP_REG_H_ */